services:
  pgsql:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  mailpit:
    image: axllent/mailpit:v1.18
    ports:
      - 1025:1025
      - 8025:8025
